#FROM osm_uzb_pgis-x86_64-linux:82wqw8784kqx9cwg1v82p3cs7dszwl2h

ADD "./postgresql.conf" "/nix/store/8zzdfa98f3dr0bilrdid757klq2vi3hw-osm-database/postgresql.conf"

# /nix/store/8zzdfa98f3dr0bilrdid757klq2vi3hw-osm-database/